### ISSUE TITLE
need to fix

### ISSUE THREAD

**Issue by makiraid** [M1n007/deno_simple_api#2]
I added docker configuration to run this app, I got an issues while running the app. #1 
![image](https://user-images.githubusercontent.com/33960326/96122177-50427b80-0f1b-11eb-8106-88d383e4b444.png)

**Comment by M1n007** [comment]
Thanks, I'll check it later.

**Comment by aceodus** [comment]
let me fix it

**Comment by aceodus** [comment]
done [https://github.com/M1n007/deno_simple_api/pull/3](https://github.com/M1n007/deno_simple_api/pull/3)

**Comment by M1n007** [comment]
> done #3

Thanks 👍
